
- name: Respaldo de Carpetas SCOT
  hosts: all 
 
  tasks: 
     - name: Respaldando Bin
       win_robocopy:
         src: C:\SCOT\Bin
         dest: C:\Despliegues\Despliegues\20180529\bk\
         recurse: yes
     - name: Respaldando Config
       win_robocopy:
         src: C:\SCOT\Config
         dest: C:\Despliegues\Despliegues\20180529\bk\
         recurse: yes
