
- name: Respaldo de Carpetas SCOT
  hosts: all 
 
  tasks: 
     - name: Respaldando Bin
       win_robocopy:
         src: C:\SCOT\Bin
         dest: C:\Despliegues\20180725\bk\bin
         recurse: yes
     - name: Respaldando Config
       win_robocopy:
         src: C:\SCOT\Config
         dest: C:\Despliegues\20180725\bk\config
         recurse: yes
