- name: Descarga de Paquetes
  hosts: all 
 
  tasks:
     - name: Descargando el Archivo CopyFile.bat
       win_get_url:
         url: http://10.32.20.110/sodimac/CopyFile.bat
         dest: C:\Despliegues\20180731\UpDate\CopyFile.bat
         
     - name: Descargando el Paquete Sodimac_LaneSetup-6.0.5.13.144.exe
       win_get_url:
         url: http://10.32.20.110/sodimac/Sodimac_LaneSetup-6.0.5.13.144.exe
         dest: C:\Despliegues\20180731\UpDate\Sodimac_LaneSetup-6.0.5.13.144.exe
