- name: Revisar Instalación
  hosts: all
  become_method: runas
 
  tasks:
      - name: retrieve the input based on stdin
        win_shell: '$string = [Console]::In.ReadToEnd(); Write-Output $string.Trim()'
        args:
          stdin: Input message
