- name: Revisar Instalación
  hosts: all
  become_method: runas
 
  tasks:
     - name: Revisión del InstalllHistory.log
       win_shell: echo >> Get-Content C:\SCOT\Install\InstallHistory.log -Tail 3 >> echo
