- name: Revisar Instalación
  hosts: all
  become_method: runas
 
  tasks:
    - win_shell: Get-Content C:\SCOT\Install\InstallHistory.log -Tail 3
      register: result
    - debug:
      msg: "Nada {{ stdout_lines }}
