- name: Proceso de Limpieza estado Inicial Maquina Windows POS
  hosts: all 
 
  tasks: 
     - name: Elimiando el archivo de 7-zip
       win_file:
         path: C:\temp\7z.msi
         state: absent
         
     - name: Limpiando el directorio
       win_file:
         path: C:\temp\
         purge: yes
  
     - name: Desistalación del 7-zip
       win_command: C:\Windows\System32\msiexec.exe /x {23170F69-40C1-2702-1701-000001000000} /qn /norestart
       

