- name: Instalación del Programa 7-zip
  hosts: all 
 
  tasks:
     - name: Descargando el Paquete de 7-Zip
       win_get_url:
         url: http://www.7-zip.org/a/7z1701-x64.msi
         dest: C:\Users\LabAnsible\7z.msi

     - name: Installando 7-zip
       win_package:
         path: C:\Users\LabAnsible\7z.msi
         product_id: "7-Zip"
         state: present
